version: "3.9"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hyperloglog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - kafka
    env_file:
      - .env

  spark-consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    env_file:
      - .env

volumes:
  postgres-data: